// vue-app/src/App.vue
<script setup>
import { ref } from 'vue'

const todos = ref([
  { id: Math.random(), name: 'Task 1', done: false },
  { id: Math.random(), name: 'Task 2', done: true },
  { id: Math.random(), name: 'Task 3', done: false },
  { id: Math.random(), name: 'Task 4', done: true },
  { id: Math.random(), name: 'Task 5', done: false },
  { id: Math.random(), name: 'Task 6', done: true }
])

function addTodo(name = '') {
  todos.value.push({ id: Math.random(), name, done: false })
}

function add1000Todos() {
  for (let i = 0; i < 1000; i++) {
    addTodo(`New task ${i}`)
  }
}

function removeTodo(index) {
  todos.value = todos.value.toSpliced(index, 1)
}
</script>

<template>
  <h1>TO-DO LIST (Vue.js)</h1>

  <ul>
    <li v-for="(todo, index) in todos" :key="todo.id">
      <input type="checkbox" v-model="todo.done" />
      <input type="text" v-model="todo.name" />
      <button @click="() => removeTodo(index)">X</button>
      {{ todo.name }}
    </li>
  </ul>

  <button @click="() => addTodo()">Add To-Do</button>
  <button @click="add1000Todos">Add 1000 To-Dos</button>
</template>

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'angular-app';
  todos = [
    { id: Math.random(), name: 'Task 1', done: false },
    { id: Math.random(), name: 'Task 2', done: true },
    { id: Math.random(), name: 'Task 3', done: false },
    { id: Math.random(), name: 'Task 4', done: true },
    { id: Math.random(), name: 'Task 5', done: false },
    { id: Math.random(), name: 'Task 6', done: true },
  ];

  addTodo(name = '') {
    this.todos.push({ id: Math.random(), name, done: false });
  }

  add1000Todos() {
    for (let i = 0; i < 1000; i++) {
      this.addTodo(`New task ${i}`);
    }
  }

  removeTodo(index: number) {
    this.todos.splice(index, 1);
  }
}

<h1>TO-DO LIST (Angular)</h1>

<ul>
  @for (todo of todos; track todo.id) {
    <li>
      <input type="checkbox" [(ngModel)]="todo.done">
      <input type="text" [(ngModel)]="todo.name">
      <button (click)="removeTodo($index)">X</button>
      {{ todo.name }}
    </li>
  }
</ul>

<button (click)="addTodo()">Add To-Do</button>
<button (click)="add1000Todos()">Add 1000 To-Dos</button>
